openapi: 3.0.2
info:
  title: Normativos do Banco Central
  description: Permite a busca de normativos do Banco Central por diversos parâmetros e acesso a detalhes de normas. As informações aqui listadas não substituem a publicação no DOU e no Sisbacen.
  version: '1.0'
  license:
    url: http://www.opendefinition.org/licenses/odc-odbl
    name: Licença Aberta para Bases de Dados (ODbL) do Open Data Commons
  contact:
    url: https://www.bcb.gov.br/acessoinformacao/faleconosco
    name: Banco Central do Brasil
servers:
  - url: https://www.bcb.gov.br/api/servico/sitebcb/ri
    description: Ambiente de produção
paths:
  /normas/busca:
    $ref: paths/normas@busca.yaml
  /normas/{id}:
    $ref: paths/normas@{id}.yaml
